# Site settings
language:               ""
title:                  "Kristian David Rogelstad"
description:            "Hello. My name is Kristian. I love bacon, hockey, woodworking and making things on the internet."
google-verification:    ""

# Handling Reading
include:
  - ".htaccess"
  - "_pages"

exclude:
  - "assets/js/app.js"
  - "assets/scss/*.scss"
  - "assets/vendor/foundation-sites/"
  - "assets/vendor/jquery/"
  - "assets/vendor/motion-ui/"
  - "assets/vendor/phpmailer/**/*.html"
  - "assets/vendor/what-input/"
  - "bower.json"
  - "composer.json"
  - "composer.lock"
  - "DOC.md"
  - "Gemfile"
  - "Gemfile.lock"
  - "gulp"
  - "gulpfile.js"
  - "LICENSE.md"
  - "Makefile"
  - "node_modules"
  - "npm-debug.log"
  - "package.json"
  - "README.md"
  - "rev-manifest.json"

# Plugins
gems:             ["jekyll-sitemap", "jekyll-paginate"]

# Conversion
incremental:      true

# Serving
# url:            ""
# baseurl:        "" # does not include hostname

# Outputting
permalink:        "/work/:year/:title/"
paginate_path:    "/work/page:num"
paginate:         18
